# 1. Setup and Imports

In [1]:
from pathlib import Path
import pandas as pd

# 2. Load Dataset
The dataset used in this project is the Online Retail dataset sourced from Kaggle. 
The CSV file is stored locally in the `/data` folder and loaded using pandas. 
The encoding is set to `ISO-8859-1` to avoid character encoding issues commonly associated with this dataset.

In [14]:
DATA_PATH = Path("../data/OnlineRetail.csv")
df_raw = pd.read_csv(DATA_PATH, encoding="ISO-8859-1")
df_raw.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# 3. Data Overview
This section examines the structure of the dataset, including data types, missing values, and summary statistics.

Basic dataset check

In [15]:
print("Rows:", df_raw.shape[0])
print("Columns:", df_raw.shape[1])
df_raw.info()
df_raw.describe()

Rows: 541909
Columns: 8
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

Preview columns and missing values

In [16]:
display(df_raw.head())
display(df_raw.isna().sum())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Check the count of unique products, customers, and invoices

In [17]:
df_raw.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

Check for duplicates records

In [18]:
df_raw.duplicated().sum()

np.int64(5268)

Check for zero or negative prices

In [19]:
df_raw[df_raw["UnitPrice"] <= 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom

Check for cancelled transactions (invoice numbers with "C")

In [20]:
df_raw[df_raw["InvoiceNo"].astype(str).str.startswith("C")].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

# 4. Data Cleaning

The dataset is processed in two stages. First, structural cleaning is performed to remove invalid records such as duplicates and entries with missing customer identifiers, resulting in a cleaned dataset (df_clean). Subsequently, a modelling dataset (df_model) is created by excluding returns and cancelled transactions to ensure that only valid sales were used for analysis. This separation allowed for both accurate modelling and the preservation of operational insights related to returns and cancellations.

Maintaining multiple dataset versions ensured that data preprocessing decisions remained transparent and reversible, while enabling different analytical perspectives.

Create clean dataset

In [21]:
df_clean = df_raw.copy()
df_clean = df_clean.dropna(subset=["CustomerID"])
df_clean = df_clean.drop_duplicates()
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

Quick validation check

In [22]:
df_clean.info()
df_clean.describe()

<class 'pandas.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  str
 1   StockCode    401604 non-null  str
 2   Description  401604 non-null  str
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[us]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 27.6 MB

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  401604.000000                      401604  401604.000000  401604.000000
mean       12.183273  2011-07-10 12:08:23.848567       3.474064   15281.160818
min    -80995.000000         2010-12-01 08:26:00       0.000000   12346.000000
25%         2.000000         2011-04-06 15:02:00       1.250000   13939.000000
50%         5.000000         2011-07-29 15:40:00       1.950000   15145.000000
75%        12.000000         2011-10-20 11:58:30       3.750000   16784.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       250.283037                         NaN      69.764035    1714.006089

# 5. Exploratory Data Analysis

# 6. Model Training

# 7. Evaluation

# 8. Save Outputs